### ISSUE TITLE
Question about Twitch Client ID & Secret

### ISSUE THREAD

**Issue by AzhamProdLive** [AbdelrhmanNile/UnderTaker141#2]
Hello there, I just saw your software and it seems very interesting to use, only issue I have with this is the mention of the Twitch ID & Secret in the readme.

My question is : Is it mandatory for the use of the app, and if yes, what do you use the ID for ?

**Comment by AbdelrhmanNile** [comment]
games's cover-art and description are fetched from igdb.com api (owned by twitch)

it is only used when you update the database to fetch new games released by jc141
i already did the heavy work and scraped more than 1000 game coverart and description and stored them in  `games_info` table inside `src/database/games.db` file 
so basically when updating the database if game already existed in the database before cover and description will be fetched from the database, if it's a new game that was not in the database, its cover and description will be fetched from igdb.com api and stored in the database

**Comment by AbdelrhmanNile** [comment]
you can use the app without configuring twitch id and secret, just dont try to update the database it will probably crash

**Comment by AzhamProdLive** [comment]
Gotcha gotcha, thanks for the explanation man :+1:
