### ISSUE TITLE
LinuxRuleZ and Debrid support

### ISSUE THREAD

**Issue by adsewadsw** [AbdelrhmanNile/UnderTaker141#3]
I haven't tried the program yet but I really like the idea :+1: 

**Is your feature request related to a problem? Please describe.**
No but it would expand the catalog a bit and provide access to "all" cracked games for Linux, I think :)

**Describe the solution you'd like**
I'd like for [LinuxRuleZ](https://forum.torrminatorr.com/memberlist.php?mode=viewprofile&u=57240)  to also be supported. He is releasing pre-configured and ready to play games on [Torrminatorr](https://forum.torrminatorr.com)

**Describe alternatives you've considered**
None. I don't know anyone besides [LinuxRuleZ](https://forum.torrminatorr.com/memberlist.php?mode=viewprofile&u=57240) and [johncena14](https://1337x.to/user/johncena141/) releasing games for Linux.

**Additional context**https://real-debrid.com/
Futhermore, support for Debrid services such as [Real-Debrid](https://real-debrid.com/) (Insterad of qBittorrent), would allow for me to use this program, since that's how I get my Torrents/Files - Real Debrid kinda acts like a tool to convert torrents into DLL files while caching them on their servers, so everyone with the service has access to the cached file.

Also, I completely understand if this is not possible or even wanted, I just though it would be cool :) ... A Flatpak would also be nice but that might deserve it's own thread.

**Comment by AbdelrhmanNile** [comment]
Hello!
getting LinuxRuleZ repacks is doable with some hard work, i might consider it in the future

as for debird i think i wont be able to do it and probably its not doable
also i cant replace qbittorrent since its used to manage the library itself, this whole UI is built on top of qbittorent api

**Comment by AbdelrhmanNile** [comment]
for flatpak i might consider it but i think it might cause problems. as far as i know flatpaks are sandboxed and probably this might introduce some problems, but i will look into it.

**Comment by adsewadsw** [comment]
I understand. I think Flatpaks should be possible, specifically since qBittorrent has a Flatpak, but that's just an assumption.  I will be following the project and looking forward to future updates :) Keep up your work!
